### PR TITLE
Feature/show ratings in profile

### LINKED ISSUE #158: Add Ratings to MySpace

### PR DESCRIPTION
**Pull request by feliperamoss**

### CODE REVIEW

**Comment by Maxiboy441** [comment]
Hey @feliperamoss,
please check this error "Argument type 'System.Tuple<string,string?,string,string,string>' is not assignable to model type 'System.Tuple<string,string,string,string,System.Tuple<string,string>,string>'" in the UserUpdate view

**Review by Maxiboy441 — CHANGES_REQUESTED** [review]
image

**Review by Maxiboy441 — CHANGES_REQUESTED** [review]
Hey, is it supposed to go "on-click" of a movie to its page or open like in the other tabs from the side? 

And when you change you rating from the my space, the window stays open after selection, is that intended?

**Comment by feliperamoss** [comment]
> Hey, is it supposed to go "on-click" of a movie to its page or open like in the other tabs from the side?
> 
> And when you change you rating from the my space, the window stays open after selection, is that intended?

It was very buggy to leave the side card for the rating tab and the rating after submit was also intended to show the modal after selection, so if user clicks by accident he/she does not need to open the modal to edit again.

**Pull request merged**
